### ISSUE TITLE
Refactor to match conventions

### ISSUE THREAD

**Issue by SeanErn** [5152Alotobots/5152_Crescendo#33]
The codebase needs to be refactored in the following ways:
- Use lowercase package names
- New folder structure to improve readability. I suggest the following:
```
java/
├─ frc/
│  ├─ robot/
│  │  ├─ subsystem/
│  │  │  ├─ arm/
│  │  │  │  ├─ commands/
│  │  │  │  │  ├─ Cmd_SubSys_Arm_JoyStickDefault.java
│  │  │  │  ├─ SubSys_Arm.java
│  │  │  │  ├─ SubSys_Arm_Constants.java
│  │  ├─ Constants.java
│  │  ├─ Main.java
│  │  ├─ Robot.java
│  │  ├─ RobotContainer.java

```

**Comment by Rkortlandt** [comment]
You need somewhere for auto cmds and cmds with many subsystems. The driverstation and auto files can be in the robot folder I made some style changes to file names so insted of Cmd_SubSys_Arm_NameOfCommand (which is long and looks like it both a command and a subsystem) to Cmd_Arm_NameOfCommand

This is what I suggest feel free to expand on it if nessisary
```
java/
├─ frc/
│  ├─ robot/
│  │  ├─ subsystem/
│  │  │  ├─ arm/
│  │  │  │  ├─ commands/
│  │  │  │  │  ├─ Cmd_Arm_NameOfCommand.java
│  │  │  │  ├─ SubSys_Arm.java
│  │  │  │  ├─ Constants_Arm.java
│  │  ├─ commands/
│  │  │  ├─ auto/
│  │  │  │  ├─ Cmd_BestAuto.java
│  │  │  ├─ teleop/
│  │  │  │  ├─ Cmd_Teleopcmd.java
│  │  ├─ DriverStation.java
│  │  ├─ Auto.java
│  │  ├─ Constants.java
│  │  ├─ Main.java
│  │  ├─ Robot.java
│  │  ├─ RobotContainer.java

```

**Comment by SeanErn** [comment]
We've never used a command for teleop before only default commands in the robotcontainer. How do you want me to do this?

**Comment by Rkortlandt** [comment]
what if you have a sequential cmd to align to the Human player station and then move the arm to the  
correct pos? This would go in the Teleop folder

**Comment by SeanErn** [comment]
ah I see

**Comment by SeanErn** [comment]
I am working on refactoring now

**Comment by Rkortlandt** [comment]
We should have a library folder for subsys we use year to year Ex)
```
java/
├─ frc/
│  ├─ robot/
│  │  ├─ subsystem/
│  │  │  ├─ arm/
│  │  │  │  ├─ commands/
│  │  │  │  │  ├─ Cmd_Arm_NameOfCommand.java
│  │  │  │  ├─ SubSys_Arm.java
│  │  │  │  ├─ Constants_Arm.java
│  │  ├─ commands/
│  │  │  ├─ auto/
│  │  │  │  ├─ Cmd_BestAuto.java
│  │  │  ├─ teleop/
│  │  │  │  ├─ Cmd_Teleopcmd.java
│  │  ├─ library/
│  │  │  ├─ swerve/
│  │  │  │  ├─ commands/
│  │  │  │  │  ├─ Cmd_Swerve_DriveDistance.java
│  │  │  │  ├─ SubSys_Swerve.java
│  │  │  │  ├─ Constants_Swerve.java
│  │  ├─ DriverStation.java
│  │  ├─ Auto.java
│  │  ├─ Constants.java
│  │  ├─ Main.java
│  │  ├─ Robot.java
│  │  ├─ RobotContainer.java
```

**Comment by SeanErn** [comment]
definitely,  I had planned on that, just forgot to add it to the layout

**Comment by Rkortlandt** [comment]
add subsystem folder should be subsystems
\

**Comment by SeanErn** [comment]
no.

**Comment by Rkortlandt** [comment]
explain

**Comment by SeanErn** [comment]
Nah yeah I'll do that lmao

**Comment by SeanErn** [comment]
Refactoring is done, the only thing else is going through and making every variable that can be final, final and changing them to use the UPPER_CASE constants convention

**Comment by chrisdeboer** [comment]
How does this folder structure compare with WPILib examples or other teams?  Did you research for best practices?  If so, please link them here.

Why did you choose to reference ORACLE Java Development Style Guide?  Do you have a link to it so others can review it?  Did you propose this as a standard?

**Comment by Rkortlandt** [comment]
Did the crescendo folder get created on your branch?

**Comment by SeanErn** [comment]
This was merged to master.
