### ISSUE TITLE
[Simulation-WPILib-ArmRotation] Add simulation capability for Arm rotation in Teleop Control

### ISSUE THREAD

**Issue by chrisdeboer** [5152Alotobots/5152_Crescendo#35]
Utilize the Physics Simulation in WPILib and create a 2D simulation of the Arm rotation.  This would be the same as the SingleJointedArmSim example.  The Arm should rotate with the joystick input like in Teleop mode.

**Comment by Rkortlandt** [comment]
After further investigation this seems unnecessary and not very possible with ctre motors and a can coder
