### ISSUE TITLE
[Architecture] Seperate Auto Files from Robot Container

### ISSUE THREAD

**Issue by chrisdeboer** [5152Alotobots/5152_Crescendo#4]

**Comment by Rkortlandt** [comment]
Just opened a branch for this and will get started

**Comment by chrisdeboer** [comment]
I think this should be a folder that contains a file for each command so that it is easy to see if a command has been changed.  there should be a "AutoCommand" file that puts each command into the drop down for selecting an Auto Command.

**Comment by Rkortlandt** [comment]
Please see the pull request where I have proposed a new class/file called "Auto" that is responsible for constructing all of the auto commands and adding them to the chooser
