### ISSUE TITLE
Bug - Shooter Range not clamped when rot to deg

### ISSUE THREAD

**Issue by Rkortlandt** [5152Alotobots/5152_Crescendo#98]
Should this not clamp to -180/360 and 0? 
```double limitAdjusted = MathUtil.clamp(degree / 360.0, -180, 0); // Limit to motor limits```

Like this
```double limitAdjusted = MathUtil.clamp(degree / 360.0, -180 / 360, 0); // Limit to motor limits```

**Comment by SeanErn** [comment]
Fix it in a branch

-Sean
________________________________
